//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public string Id { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> issue_date { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Device Device { get; set; }
    }
}
